### ISSUE TITLE
Android Auto initilization silently closes/prempts wigle app process.

### ISSUE THREAD

**Issue by cognitive-rift** [wiglenet/wigle-wifi-wardriving#379]
Android 10 with Latest Android Auto and Wigle application on Pixel 3.

Step 1. Open Wigle wardriving app, let it fade into background.

Step 2. Turn on vehicle that Android Auto is paired with.

Step 3. As soon as Android Auto goes into driving mode, the Wigle app process is closed.

Expected behavior is that the Wigle app will run continuously until closed. In reality, wigle has to be re-opened every time driving mode is activated.

**Comment by bobzilladev** [comment]
We have never tested with android auto, so it's a miracle it works at all! I'll link this to your other issue and close this one.
https://github.com/wiglenet/wigle-wifi-wardriving/issues/272

**Comment by KoalaBear84** [comment]
This one should be opened again. It's not running ONTO Android Auto, it is crashing when Android Auto starts. Short after the display is taken over by the car display. And because of this bug I missed a lot of Wifi, because I thought it was started, but it had silently crashed.

Where can I find the (crash) logs (if any)? So I can update #272 

Thanks!

**Comment by rksh** [comment]
I think we have a candidate for this - seeing onDestroy getting called during theme switch even without Android Auto - very likely the same issue.

**Comment by KoalaBear84** [comment]
That is some great news. 👍

**Comment by KoalaBear84** [comment]
Any idea when this will be released?

**Comment by rksh** [comment]
This is now released - testing and feedback welcome

**Comment by KoalaBear84** [comment]
Tested it today, it works! Wigle stays alive 👍
