### ISSUE TITLE
Incorrect timestamps in database

### ISSUE THREAD

**Issue by p182** [wiglenet/wigle-wifi-wardriving#401]
Hi, today I'm exported database of my discovered networks, but timestamps seems incorrect (for example 2000-06-16T11:44:18+0400 instead 2020-01-31T11:44:18+0400).
Why is this happening and how to fix it?
P. S. Phone has correct date/time settings and other apps (like G-Mon) show time normally.

**Comment by goldfndr** [comment]
That looks like the interval of [the rollover](https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover) (19.7 years).

**Comment by bobzilladev** [comment]
That data comes from the timestamp of the gps locations, likely it didn't have a solid lock at that time. The accuracy number may also be...large.

**Comment by p182** [comment]
It's my phone's or application issue? Maybe we can make check, for example if GPS and device time differ more than some time interval then use phone time? Or detect possible rollovers and automatically correct time (first check device time and if it gets into GPS rollover then count from time of rollover)?

**Comment by solsticedhiver** [comment]
I just noticed that the timestamp in the csv file are in local time.
Is this intended ?
Because I wonder how you are dealing with that, server side ? It is a mess, or you do not deal with it all ? because there is no way to know the timezone in the csv ??

So maybe use **Instant** instead of **Date** in the code ? https://stackoverflow.com/a/19632076/283067

**Comment by rksh** [comment]
closing absent a counterexample - please feel free to file a new ticket referencing this item if the above answer is incorrect or incomplete!
