### ISSUE TITLE
Convenient localization

### ISSUE THREAD

**Issue by KovalevArtem** [wiglenet/wigle-wifi-wardriving#431]
I suggest you start using a full-fledged translation platform.
This will greatly simplify the translation process. And I'm sure it will bring support for even more languages ​​for the application ...

I suggest using Weblate, an open source platform. It's free to use for open source projects.
![image](https://user-images.githubusercontent.com/36500228/91071200-9298bc00-e640-11ea-8fde-0b58942c86c8.png)
![image](https://user-images.githubusercontent.com/36500228/91071418-d12e7680-e640-11ea-8036-9e68c260ec89.png)

**Comment by rksh** [comment]
is this a recommendation for the Android client or the Website?

**Comment by KovalevArtem** [comment]
Website

**Comment by rksh** [comment]
closing this issue as
1. this issue is under discussion in other forums and
2. this tracker is for the Android client, not the website.

**Comment by KovalevArtem** [comment]
You're right. I apologize. 😔 (I wrote about the translation of the site elsewhere)
This issue related to the Android application!

**Comment by rksh** [comment]
The strings.xml files will be managed directly via github - we won't be porting those to any translation frameworks for the app in the foreseeable future. People are welcome to use any frameworks they prefer outside of the source control provided the output is a standard SDK16-and-up compatible strings.xml file. The default strings.xml will continue to be en-US equivalent since that's the language of all feature development to-date, and should considered the canonical file. We're undertaking an effort to clean up and organize the existing strings.xml files to make this process easier.  We won't be accepting commits of i18n/l18n changes in other formats that dictate our tech choices.

 We're in the process of evaluating choices for localization of the site thanks to your input! Since the site is not open-source, and since our back-end has i18n/l18n built in, we'll be selecting something compatible with existing choices.
