### ISSUE TITLE
persistent keep screen on option

### ISSUE THREAD

**Issue by clientenq** [wiglenet/wigle-wifi-wardriving#433]
By default the screen is automatically controlled via system preferences. These preferences can be related to permission settings like ability to use resources such as device location.
The user can select the option to disable automatic control via the keep screen on option.

When maps is displayed from wigle (via maps or via result details) the option can get a reset without direct user control and without clear notification to the user. This impacts the operation of wigle and the results. Since in screen on mode the controls are not locked this can have even more impact when maps or details are selected by accident.

As a feature request I hope wigle can prevent the override of the keep screen on option via display of maps or at least notify the user when this setting changes without the user interacting with the menu.

**Comment by rksh** [comment]
I don't see the preference getting changed by visiting activities or fragments containing maps - only the screen being allowed to shut off in spite of the preference.

What's more/more interesting is that this DOESN'T appear to happen on the MappingFragment OR the new Search fragment (which contains a map)- only on the search results and network detail activities. The app is mostly implemented with a Fragment manager based on the `MainActivity` but it contains the following independent activities:

`net.wigle.wigleandroid.MacFilterActivity`
`net.wigle.wigleandroid.FilterActivity`
`net.wigle.wigleandroid.NetworkActivity`
`net.wigle.wigleandroid.SpeechActivity`
`net.wigle.wigleandroid.DBResultActivity`
`net.wigle.wigleandroid.MapFilterActivity`
`net.wigle.wigleandroid.RegistrationActivity`
`net.wigle.wigleandroid.GpxManagementActivity`
`net.wigle.wigleandroid.SpeechActivity`
`net.wigle.wigleandroid.ActivitateActivity`
`net.wigle.wigleandroid.DebugActivity`
`net.wigle.wigleandroid.ErrorReportActivity`

my take is:
 We _should_ override the timeout in common "app usage" activityies: `MacFilterActivity`, `FilterActivity`, `MapFilterActivity`,  `NetworkActivity`, and _maybe_ `DBResultActivity`/`GpxManagementActivity`.
 
 I think we should avoid overriding the behavior in the other for several reasons, but largely because they're part of the process of configuring the app, not regular usage (and because the camera pane in the Activate Activity drains a phone's battery quite quickly)

**Comment by rksh** [comment]
Update - this isn't a preference at all - only a global state element. This means you have to re-activate it on each run of the application. I'll be remedying this with current behavior - but it's possible that this _should_ be a preference. If this is the case that should be filed as an independent ticket.

The current `PowerManager.WakeLock` is held in the `MainActivity` which is paused and resumed when other activities are launched. The result releases and restores the WakeLock there according to the global state setting `onPause` and `onResume`. Rather than risk this leaking and because the "new" approved way of doing this relies on `Window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON`, I'm going to move the list of "usage" activities above to respect the `MainActivity.state.screenLocked` flag, with the exception of Dashboard which remains on regardless.

**Comment by rksh** [comment]
https://github.com/wiglenet/wigle-wifi-wardriving/pull/643 fixes the core problem.

**Comment by rksh** [comment]
will be fixed in release 2.81
