### ISSUE TITLE
Launch Wigle at boot is not working on Android 11

### ISSUE THREAD

**Issue by DaniloNC** [wiglenet/wigle-wifi-wardriving#435]
Wigle won't start during boot on Android 11 when `Launch Wigle at boot` option is marked.
I am not sure if that was working on Android 10 but that was working on Android 9.

Tested on `Pixel 2` and `Pixel 4a` running `Wigle 2.55 beta`, Android 11 fully updated.

**Comment by rksh** [comment]
this took us a while, but this is fixed in https://github.com/wiglenet/wigle-wifi-wardriving/pull/550 (will be in v2.68).
Note that the permission prompt here will direct you to the preferences pane where you have to manually allow WiGLE to "draw over" other apps, a consequence of UI apps that start on boot beginning in Android 10!
