### ISSUE TITLE
feature request: SSID filter ; delete DB ;  show version

### ISSUE THREAD

**Issue by meoso** [wiglenet/wigle-wifi-wardriving#45]
These may exist but i cannot locate them:

feature request 1)
In the past i used an option that would filter out a specific SSID as to not save/upload it.  I would like to have this ability again.  I would also like to filter more than one SSID.

feature request 2)
please add a delete database button.

feature request 3)
please display version number somewhere.

**Comment by bobzilladev** [comment]
1) This feature never existed in our app, but we probably could add it. Similar to the BSSID filter in https://github.com/wiglenet/wigle-wifi-wardriving/issues/58
2) You can delete the database by deleting the wigle/wiglewifi.sqlite file on the sd card, if stored there, otherwise deleting the app's data via the android settings. This is a pretty dangerous feature that we wouldn't want to add.
3) You can see the version in the android settings under the app settings. We could probably show it on the settings screen though.

**Comment by meoso** [comment]
Thank you,
please proceed with #1 (blacklist filter BSSID)

**Comment by rksh** [comment]
Database delete and filter BSSID options implemented!
