### ISSUE TITLE
Less aggressive "No Play Services" dialog

### ISSUE THREAD

**Issue by eda-abec** [wiglenet/wigle-wifi-wardriving#485]
I don't have Play Services on my device and so the app notifies me about it on start ("WiGLE WIFI Wardriving won't run without Google Play services,..."). That is fine on first run, but it would be nice if the user didn't have to acknowledge it on every launch of the app. :)

Note: I tried both main and FOSS version.

**Comment by bobzilladev** [comment]
That dialog comes from the built in libraries, I don't think we have any control over it. There is a FOSS version of the play services so it's still there, but we just had to remove all the mapping infrastructure in FOSS land.

**Comment by rksh** [comment]
Further research indicates this will happen every time we make any call related to the library. Closing this issue since FOSS version does avoid the dialog, resolving the OP's question (and sans Play services, we can't do a number of things we do in the Play Store binary). Further feedback welcome in a new ticket.
