### ISSUE TITLE
The app's layout shows arrows from the drop-down menu in the navigation menu as you scroll

### ISSUE THREAD

**Issue by olekstomek** [wiglenet/wigle-wifi-wardriving#519]
It looks weird, and I think you can best see it in the attachments below (don't worry about the language of the application as it doesn't matter for this problem).

![1650408122943](https://user-images.githubusercontent.com/26818304/164115027-8bdca9c1-22ca-419b-97e3-e494121548e5.jpg)

https://user-images.githubusercontent.com/26818304/164115045-0fb6a145-2d7f-40cb-b75a-01aa3fda6ec5.mp4

A problem that is always repeated.

Version of app 2.64
Android 11
Xiaomi Mi 9

**Comment by rksh** [comment]
yikes. That's a seriously strange interaction. We're not doing anything weird with Android's scrolling views (on the settings page, at least), so that's a surprise. As people see this issue,, please post what OS-version and device you've tested on, and whether or not it occurs with your device..

For me:
Samsung Galaxy A10e / Android 11: yes
Samsung ZFlip / Android 12: yes
Pixel 5 / Android 12: yes (minimal area, hard to see)
Moto Z 1 / Android 8: yes

**Comment by olekstomek** [comment]
It is interesting that the problem doesn't always occur - at the beginning of the recording in my first post you can see that everything is OK.
I checked on old Android and the problem doesn't occur:
Motorola Moto G / Android 5.1:**no**

**Comment by pejacoby** [comment]
Also seeing in v2.6.5 on a Samsung S9 with Android 10 and One UI v2.5..

As you scroll down the settings screen the Scan and GPS pop-up menu down arrows appear in the navigation menu, and then flash a second arrow as your near the bottom and scroll back upwards as well.  The second arrow sometimes goes away when you pause after a few seconds, sometimes not.


![IMG_0618](https://user-images.githubusercontent.com/16978661/194677425-02d0d5db-f695-47a7-89f1-2e843c6355aa.jpg)

**Comment by rksh** [comment]
https://stackoverflow.com/questions/45442578/scrollview-and-spinner/46964155#46964155 - the answer appears to fix it with test devices. Not the kind of deterministic fix we prefer (*why* does it work??), but we'll apply this.

**Comment by rksh** [comment]
will be fixed in release 2.72
