### ISSUE TITLE
Submit to Mozilla Location Service

### ISSUE THREAD

**Issue by pgn674** [wiglenet/wigle-wifi-wardriving#547]
[Mozilla Location Service](https://location.services.mozilla.com/) (MLS) is a geolocation querying service, used by the Linux desktop environment GNOME's [geoclue](https://gitlab.freedesktop.org/geoclue/geoclue/-/wikis/home) program. Currently, there's no good way to submit Wi-Fi locations to MLS, though the database is still actively used for laptop Linux location services. There used to be an Android app called [Stumbler](https://discourse.mozilla.org/t/retiring-mozilla-stumbler/75206), but that's been removed, and the Firefox app no [longer has the feature](https://wiki.mozilla.org/CloudServices/Location/Software).

Can an MLS submission feature be added to the WiGLE app? Even it was a background, secondary, low priority, infrequent thing, disconnected from WiGLE's primary functions, it'd be tremendously helpful to the MLS database.

Personally, I moved 2 years ago and brought my Wi-Fi router with me, but my Linux laptop still says I'm back at my old house.

The MLS data submission API is documented here: https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html

**Comment by rksh** [comment]
First of all - the data you collect with the app is your own - we offer a plethora of options in the "Database" activity that can get you current or all-time records as:
 - SQLite (the native storage format)
 - KML
 - CSV
 there's also individual uploads-level CSV and KML record access in the "button" on the upload page if you choose to upload.
Anything that can morph those into the required upload format will do the trick!
Since adding all the language translations for a new UI feature or Setting-fragment element to the app is rather a lot of work, it's worth looking at simple scripts that can convert those into the upload format externally.

Secondly: we're not big fans of uploading to *anything* without specific user action (even to us) - we allow people to script that via Android intents, but we ask that people configure when/where to upload data for privacy and security reasons. If you decide to implement in your own fork or submit a PR, we urge you to consider using the Broadcast Intent framework to make sure the app doesn't upload without user intention.

All this being said, pull requests are very welcome, and we love supporting the free software community when and where we can, especially Mozilla!

**Comment by bobzilladev** [comment]
This mozilla project seems to have been mostly retired in 2021, but we'll leave this issue open for a while longer.

**Comment by rredford6** [comment]
Mozilla is retiring the APIs: https://github.com/mozilla/ichnaea/issues/2065
