### ISSUE TITLE
Unable to upload to wigle since Let's encrypt is used

### ISSUE THREAD

**Issue by cdman** [wiglenet/wigle-wifi-wardriving#65]
I have an old phone (Android 2.2) which I occasionally use to capture and upload location data (I'm current #708 - user "cdman").

Unfortunately my phone does not have the Lets encrypt root certificate and as such it can't upload to wigle.net (it gives an SSL error). Perhaps we could add the the root certificate as a "custom certificate" as described here: http://nelenkov.blogspot.ro/2011/12/using-custom-certificate-trust-store-on.html (the section starting with "creating a custom TrustManager that delegates certificate checks to the system default one and uses the local trust store if verification fails. Here's how this looks like" seems to be the relevant one).

**Comment by bobzilladev** [comment]
Another user on an old version ran into this. If the device is rooted you can backport a cert list (cacerts.bks) from a newer android to the older one. The last post here has more details:
https://wigle.net/phpbb/viewtopic.php?f=5&t=2325&p=8698

We can look into packaging the cert along with the app, we used to do that years ago. Not sure if we have a device with the right version to test with. The google compatibility library only goes back to 2.3, and 2.3.6 has the required trusted cert installed. What version of Wigle Wifi are you running? Since 2.2 isn't supported anymore, I'm guessing a rather old version that it would be hard to patch at this point since all the tooling has changed.

**Comment by cdman** [comment]
Hmm, it seems that I have to bite the bullet and either root the phone or get a new phone. It's sad how quickly updates are discontinued for phones.

For reference my phone is a Motorola MB525 with Android 2.2.2 and the Wigle version I'm using is version 2.4.
