### ISSUE TITLE
Custom identifiers in the wigle wifi csv file name

### ISSUE THREAD

**Issue by 463N7** [wiglenet/wigle-wifi-wardriving#694]
Adding a way to add some sort of identifier to each of my phones CVS names so that after uploading i can easily see which device uploaded which file.

I personally would just want each file name to contain what model of phone uploaded it. for example "Nexus6p_DATETIME.csv"

I think this could be done with a text box to amend the file name for each device. but maybe just a selector of a few options (android version, phone model, ect) to try an prevent people from making it something that could prevent people from leaking something private.

As it is now users can upload csv's from other systems with what ever name they want so I believe a text box would be fine.

**Comment by rksh** [comment]
would it be more helpful if we exposed mfgr/make/android version on the upload page?

**Comment by 463N7** [comment]
> upload

Yes that would help. And looks like y'all did?

**Comment by rksh** [comment]
So, we like the uploads-page solution because it uses verified information from the header file instead self-reported, works with existing data and files, and it saves folks from having to manage an input per-device to do it... does this resolve this request, or does this feature have other utility we should address?

![Screenshot 2024-03-24 at 3 31 20 PM](https://github.com/wiglenet/wigle-wifi-wardriving/assets/880022/1980e05e-9883-436d-a83f-63b0775c25a4)

**Comment by rksh** [comment]
closing as resolved.
