### ISSUE TITLE
GPS signal doesn't work on Android 11

### ISSUE THREAD

**Issue by GamePlayer-8** [wiglenet/wigle-wifi-wardriving#701]
Good morning,

I've got a problem with WiGLE Android app not recognizing GNSS / GPS location on the stock Android 11, on Samsung Galaxy A40.

Other apps can quickly get a GPS data.
WiFi, Bluetooth and mobile network can be detected though.

**Comment by rksh** [comment]
Check the application permissions - if you dismissed the dialogs without granting "coarse" and "fine" location access, you'll be stuck. The app has been extensively tested on Android 11 and works in regular use.

**Comment by rksh** [comment]
Use "Network Location Provider" is an in-app setting, not an OS-level permission granted to the application. To enable GPS location for the application, you'll need to use the Device Settings application, select the application from the list of applications, and grant the permission you denied when you first launched the application after installing it.

**Comment by rksh** [comment]
I've retested on all my Android 11 devices (including a Samsung, although not an A40), and looked through the upload logs. GPS location works fine on all these devices, and folks are using the application successfully on A40s daily. My Samsung simply calls the permissions "Location." Whatever the problem is, it's specific to your device/setup and not to the application.
